{
 "title": "OpenBaton Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(instance)" },
   {
    "name": "instanceId",
    "label": "Instance ID",
    "query": "label_values(openbaton_nsr_count{instance=\"$node\"}, instanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$node\",instanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Tomcat current threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Average API response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(http_server_requests_seconds_sum{instance=\"$node\"}[5m]) / rate(http_server_requests_seconds_count{instance=\"$node\"}[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, irate(http_server_requests_seconds_count{instance=\"$node\"}[5m]) * 60 / 4) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$node\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Logback (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$node\"}[5m]) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "JVM Classes loaded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 13, "y": 22 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"OpenBaton_NFVO\", instance=\"$node\"}*1000"
    }
   ]
  },
  {
   "title": "App up time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 13, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"OpenBaton_NFVO\", instanceId=\"$instanceId\", instance=\"$node\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"OpenBaton_NFVO\",instance=\"$node\", instanceId=\"$instanceId\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"OpenBaton_NFVO\", instance=\"$node\", instanceId=\"$instanceId\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"OpenBaton_NFVO\",instance=\"$node\", instanceId=\"$instanceId\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Current instance ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 26 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\"}) by (instanceId)",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Tomcat bytes sent/received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_sent_bytes_total{instance=\"$node\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "-1 * irate(tomcat_global_received_bytes_total[5m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "NSR count by emsStatus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\"}) by (emsStatus)",
     "legendFormat": "{{emsStatus}}"
    }
   ]
  },
  {
   "title": "All NSR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Allocating",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\",status=\"ALLOCATE\"})"
    }
   ]
  },
  {
   "title": "EMS status error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\",emsStatus=\"ERROR\"})"
    }
   ]
  },
  {
   "title": "NSR count by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\",status=\"ERROR\"})"
    }
   ]
  },
  {
   "title": "NSR count by VNF type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openbaton_nsr_count{instance=\"$node\"}) by (vnfType)",
     "legendFormat": "{{vnfType}}"
    }
   ]
  }
 ]
}