version: "3.6"

services:
  generator:
    image: matjaz99/call-gen:v1
    environment:
      ENV_ELASTICSEARCH_HOST: 192.168.1.207
      ENV_ELASTICSEARCH_PORT: 9200
    deploy:
      mode: replicated
      replicas: 1