version: "3.6"

services:

  generator-london:
    image: matjaz99/call-gen:v1
    environment:
      ELASTICSEARCH_HOST: 192.168.1.207
      ELASTICSEARCH_PORT: 9200
      CALLGEN_NODE_LOCATION: London
      CALLGEN_MAX_INTERVAL: 25
    deploy:
      mode: replicated
      replicas: 1

  generator-berlin:
    image: matjaz99/call-gen:v1
    environment:
      ELASTICSEARCH_HOST: 192.168.1.207
      ELASTICSEARCH_PORT: 9200
      CALLGEN_NODE_LOCATION: Berlin
      CALLGEN_MAX_INTERVAL: 20
    deploy:
      mode: replicated
      replicas: 1

  generator-moscow:
    image: matjaz99/call-gen:v1
    environment:
      ELASTICSEARCH_HOST: 192.168.1.207
      ELASTICSEARCH_PORT: 9200
      CALLGEN_NODE_LOCATION: Moscow
      CALLGEN_MAX_INTERVAL: 15
    deploy:
      mode: replicated
      replicas: 1
