version: '3.6'

networks:
  prometheus-network:
    driver: overlay
    attachable: true

volumes:
  grafana_storage:
    driver: local
  prometheus_storage:
    driver: local

services:

  node-exporter:
    #image: prom/node-exporter:v0.17.0
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - prometheus-network
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus:v2.5.0
    ports:
      - 9090:9090
    networks:
      - prometheus-network
    command:
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus_data'
      - '--storage.tsdb.retention=15d'
    volumes:
      - prometheus_storage:/prometheus_data
    user: root
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana:5.4.2
    networks:
      - prometheus-network
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1

