version: '3.6'

networks:
  prometheus-network:
    driver: overlay
    attachable: true

volumes:
  grafana_storage:
    driver: local
  prometheus_storage:
    driver: local

configs:
  prometheus_config:
    file: ./prometheus_config/prometheus.yml

services:

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    networks:
      - prometheus-network
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus:v2.10.0
    ports:
      - 9090:9090
    networks:
      - prometheus-network
    command:
      - '--config.file=/prometheus_config/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus_data'
      - '--storage.tsdb.retention=15d'
    volumes:
      - prometheus_storage:/prometheus_data
    configs:
      - source: prometheus_config
        target: /prometheus_config/prometheus.yml
    user: root
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana:6.2.5
    networks:
      - prometheus-network
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1

  cadvisor:
    image: google/cadvisor:v0.32.0
    networks:
      - prometheus-network
    ports:
      - 9080:8080
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
