version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:

  traefik:
    image: traefik:1.7.12-alpine
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entryPoints=Name:https Address::443"
      - "--defaultentrypoints=https,http"
      - "--logLevel=DEBUG"
      - "--accessLog"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=swarm.cloud.local"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    ports:
      - 443:443
      - 80:80
      - 8085:8080
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
