{
 "title": "Docker Swarm Node Services",
 "description": "Docker Swarm stacks and services metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Swarm Node",
    "query": "node_meta{in_swarm!=\"false\"}"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_node_id))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\"} * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\"} * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen[5m]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Service Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_last_seen[5m]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) * 100 / count(node_cpu{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) "
    }
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (name)) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/docker/.*\"} * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "sum(container_memory_cache{id=~\"/docker/.*\"} * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable / node_memory_MemTotal) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(container_memory_usage_bytes{id=~\"/docker/.*\"}[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network received by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network transmitted by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "Transmited"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total[$interval]) )",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total[$interval])) ",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 54 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_free{mountpoint=\"/\", fstype=\"rootfs\"} / node_filesystem_size{mountpoint=\"/\", fstype=\"rootfs\"}) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  }
 ]
}