version: '3.6'

networks:
  agent_network:
    driver: overlay
    attachable: true

services:

  httpd:
    image: httpd:2.4
    ports:
      - 8070:80
    networks:
      - agent_network
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    deploy:
      mode: replicated
      replicas: 1
