version: '3.6'

networks:
  webnet:
    driver: overlay
    attachable: true

services:
  web:
    image: gitlab.iskratel.si:4567/mcrk/hello-php/master:1.0.0
    #image: matjaz99/hello-php:1.0.0
    networks:
      - webnet
    ports:
      - 8888:80
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
