{
 "title": "DockerBaton dashboard",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Running containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dockerbaton_containers_state_by_host{state=\"running\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Running containers (all hosts)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dockerbaton_containers_state_all_hosts{state=\"running\"}"
    }
   ]
  },
  {
   "title": "Nonzeroexited containers (all hosts)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dockerbaton_containers_state_all_hosts{state=\"nozeroexited\"}"
    }
   ]
  },
  {
   "title": "Managers all",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dockerbaton_swarm_manager_count"
    }
   ]
  },
  {
   "title": "Workers all",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dockerbaton_swarm_worker_count" }
   ]
  },
  {
   "title": "Managers online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dockerbaton_swarm_manager_status{status=\"ready\"})"
    }
   ]
  },
  {
   "title": "Workers online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(dockerbaton_swarm_workers_status{status=\"ready\"})"
    }
   ]
  },
  {
   "title": "Running replicas by stack",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dockerbaton_services_replicas_running) by (service_stack)",
     "legendFormat": "{{service_stack}}"
    }
   ]
  },
  {
   "title": "Replicas: prom",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dockerbaton_services_replicas_running{service_stack=\"prom\"}) / sum(dockerbaton_services_replicas_requested{service_stack=\"prom\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas: ob",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dockerbaton_services_replicas_running{service_stack=\"ob\"}) / sum(dockerbaton_services_replicas_requested{service_stack=\"ob\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas: portainer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dockerbaton_services_replicas_running{service_stack=\"portainer\"}) / sum(dockerbaton_services_replicas_requested{service_stack=\"portainer\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas: docker_baton",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dockerbaton_services_replicas_running{service_stack=\"docker_baton\"}) / sum(dockerbaton_services_replicas_requested{service_stack=\"docker_baton\"}) * 100"
    }
   ]
  }
 ]
}