{
 "title": "DTools",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Incoming webhook messages by method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtools_webhook_messages_received_total",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Webhook GET msg received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dtools_webhook_messages_received_total{method=\"get\"})"
    }
   ]
  },
  {
   "title": "Webhook POST msg received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dtools_webhook_messages_received_total{method=\"post\"})"
    }
   ]
  },
  {
   "title": "Webhook msg receive rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(dtools_webhook_messages_received_total[5m]))"
    }
   ]
  },
  {
   "title": "Alerts received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dtools_am_alerts_received_total)"
    }
   ]
  },
  {
   "title": "Incoming webhook messages by method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dtools_webhook_messages_received_total[1m])) by (method) * 60 / 4",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Alerts received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count_over_time(dtools_am_alerts_received_total[10m]))"
    }
   ]
  },
  {
   "title": "Incoming webhook messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(dtools_webhook_messages_received_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Incoming alertmanager alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dtools_am_alerts_received_total[5m])) by (severity) * 60 / 4",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}