{
 "title": "PMON - Calls by release cause",
 "time": { "from": "2018-09-17T22:23:43.142Z", "to": "2018-09-17T22:53:43.142Z" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": "label_values(nodeId)" },
   { "name": "trafficType", "label": "trafficType", "query": "label_values(trafficType)" }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "content": "### Counters" },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "content": "### Gauges" },
  {
   "title": "Total number of processed cdr records",
   "type": "graph",
   "description": "The total number of processed CDR records since PMON start.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmon_cdr_records_processed_total{nodeId=\"$node\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Rate of processing (per second)",
   "type": "graph",
   "description": "An average rate in seconds over last 5 minutes of processed CDR records. If 60 CDR records were generated in 1 min it means 1 CDR per second (in average).",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pmon_cdr_records_processed_total{nodeId=\"$node\"}[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Number of processed cdr records",
   "type": "graph",
   "description": "Number of processed CDR records in last interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmon_cdr_records_processed{nodeId=\"$node\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total number of calls by release cause",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\"}) by (callReleaseCause)",
     "legendFormat": "{{callReleaseCause}}"
    }
   ]
  },
  {
   "title": "Calls by release cause",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\"}) by (callReleaseCause)",
     "legendFormat": "{{callReleaseCause}}"
    }
   ]
  },
  {
   "title": "All calls",
   "type": "singlestat",
   "description": "Total number of calls since PMON start",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "Successful calls",
   "type": "singlestat",
   "description": "Total number of successful calls since PMON start",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Normal\"})"
    }
   ]
  },
  {
   "title": "ASR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Normal\"}) / sum(pmon_cdr_calls_total{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "NER",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=~\"Normal|User busy|No reply\"}) / sum(pmon_cdr_calls_total{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "singlestat",
   "description": "Number of calls in last interval",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "Successful calls",
   "type": "singlestat",
   "description": "Number of successful calls in last interval",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Normal\"})"
    }
   ]
  },
  {
   "title": "ASR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Normal\"}) / sum(pmon_cdr_calls{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "NER",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=~\"Normal|User busy|No reply\"}) / sum(pmon_cdr_calls{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "Total number of calls by release cause",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Normal\"})",
     "legendFormat": "Normal"
    },
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"User busy\"})",
     "legendFormat": "User busy"
    },
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"No reply\"})",
     "legendFormat": "No answer"
    },
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Call rejected\"})",
     "legendFormat": "Call rejected"
    },
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Incomplete dial\"})",
     "legendFormat": "Incomplete dial"
    },
    {
     "expr": "sum(pmon_cdr_calls_total{nodeId=\"$node\",callReleaseCause=\"Other\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Number of calls by release cause",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Normal\"})",
     "legendFormat": "Normal"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"User busy\"})",
     "legendFormat": "User busy"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"No reply\"})",
     "legendFormat": "No answer"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Call rejected\"})",
     "legendFormat": "Call rejected"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Incomplete dial\"})",
     "legendFormat": "Incomplete dial"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Other\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Total Calls duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmon_cdr_calls_duration_total{nodeId=\"$node\"}",
     "legendFormat": "Total duration (sec)"
    }
   ]
  },
  {
   "title": "Calls duration rate",
   "type": "graph",
   "description": "This graph shows duration of calls per interval (must multiply by 60 to get values for 1 min intervals - if scraping is also 1 min). If irate returns the value change per second, then following the rate should give the same result in observed interval as gauge for last scrape. Example: you can sample: 0, 5, 10, 15, 20... i know that the next value will be 25 because I know the rate of change.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pmon_cdr_calls_duration_total{nodeId=\"$node\"}[5m]) * 60",
     "legendFormat": "Total duration (sec)"
    }
   ]
  },
  {
   "title": "Calls duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmon_cdr_calls_duration{nodeId=\"$node\"}",
     "legendFormat": "Duration (sec)"
    }
   ]
  },
  {
   "title": "Calls duration in last interval (in seconds)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_duration{nodeId=\"$node\"})"
    }
   ]
  },
  {
   "title": "Average call duration (in seconds per call)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls_duration{nodeId=\"$node\"}) / sum(pmon_cdr_calls{nodeId=\"$node\",callReleaseCause=\"Normal\"})"
    }
   ]
  },
  {
   "title": "Calls by traffic type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",trafficType=\"Incoming_call\"})",
     "legendFormat": "Incoming_call"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",trafficType=\"Outgoing_call\"})",
     "legendFormat": "Outgoing_call"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",trafficType=\"Transit_call\"})",
     "legendFormat": "Transit_call"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",trafficType=\"Local_call\"})",
     "legendFormat": "Local_call"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\",trafficType=\"Unknown\"})",
     "legendFormat": "Incomplete dial"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\"}) by (callReleaseCause)"
    },
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\"}) by (trafficType)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(pmon_cdr_calls{nodeId=\"$node\"}) by (callReleaseCause)",
     "legendFormat": "{{callReleaseCause}}"
    }
   ]
  }
 ]
}