{
 "title": "Server monitor",
 "tags": [ "server" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": "label_values(instance)" },
   { "name": "netinterface", "label": "netinterface", "query": "label_values(device)" }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",mode!=\"idle\"}[5m])) by (cpu)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Procs running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "All CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",instance=\"$node\",mode=\"idle\"}[5m]))"
    }
   ]
  },
  { "title": "Alarms", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Sockets used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time()-node_boot_time_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$node\"}[5m])) by (device)",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "-1 * sum(irate(node_disk_written_bytes_total{instance=\"$node\"}[5m])) by (device)",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  {
   "title": "Network I/O (eth0)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!=\"lo\",instance=\"$node\"}[5m])) by (device)",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!=\"lo\",instance=\"$node\"}[5m])) by (device)",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "CPU average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{device=\"rootfs\",instance=\"$node\",mountpoint=\"/\"} - node_filesystem_free_bytes{device=\"rootfs\",instance=\"$node\",mountpoint=\"/\"}) / node_filesystem_size_bytes{device=\"rootfs\",instance=\"$node\",mountpoint=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Up status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "ICMP IN",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_netstat_Icmp_InMsgs{instance=\"$node\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "ICMP OUT",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_netstat_Icmp_OutMsgs{instance=\"$node\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=\"$node\",job=\"node\"}"
    }
   ]
  },
  { "title": "Server IP", "type": "text", "gridPos": { "h": 2, "w": 6, "x": 12, "y": 15 }, "content": "# $node" },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=~\"0|1\",instance=\"$node\",mode=~\"system|user\"}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=\"$node\",job=\"node\"}"
    }
   ]
  }
 ]
}