{
 "title": "Docker Swarm Nodes",
 "description": "Docker Swarm nodes metrics",
 "tags": [
  "swarm",
  "docker",
  "nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Swarm Node",
    "query": "node_meta{in_swarm!=\"false\"}"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, sum((node_time_seconds - node_boot_time_seconds) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Swarm Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) "
    }
   ]
  },
  {
   "title": "System Load by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load5 * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "load5 {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval])  * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"} * 100) by (node_name))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"rootfs\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/\", fstype=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"rootfs\"}) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Used {{node_name}}"
    },
    {
     "expr": "sum(node_memory_Cached_bytes * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Cached {{node_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Read {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Written {{node_name}}"
    }
   ]
  },
  {
   "title": "IOPS by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Reads {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"}) by (node_name)",
     "legendFormat": "Writes {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU IO Wait by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[$interval])  * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\", in_swarm!=\"false\"} * 100) by (node_name))",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}