{
 "title": "Docker Swarm Containers",
 "tags": [
  "swarm",
  "docker",
  "containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Swarm Node",
    "query": "node_meta{in_swarm!=\"false\"}"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance))"
    }
   ]
  },
  {
   "title": "Containers Network Traffic by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (node_name)",
     "legendFormat": "IN {{node_name}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) min(node_meta{node_name=~\"$node_name\"}) without(instance)) by (node_name)",
     "legendFormat": "OUT {{node_name}}"
    }
   ]
  }
 ]
}