{
 "title": "IRM - HTTP requests",
 "tags": [
  "irm",
  "springboot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average response time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum) / sum(http_server_requests_seconds_count) * 1000"
    }
   ]
  },
  {
   "title": "Top 5 URIs with slowest average response time (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds_sum / http_server_requests_seconds_count) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Activity by URI (stacked)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{status=\"200\"}[1m]) * 15",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Number of requests by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count[1m])) by (status) * 15",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Top 10 most visited URIs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(http_server_requests_seconds_count[1m])) by (uri)) * 15",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_sessions_created_sessions_total[5m])",
     "legendFormat": "Created"
    },
    {
     "expr": "irate(tomcat_sessions_expired_sessions_total[5m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "irate(tomcat_sessions_rejected_sessions_total[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Active JDBC connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(jdbc_connections_active)" }
   ]
  },
  {
   "title": "JVM treads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_states_threads", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "System load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "Received/Transmited bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_global_sent_bytes_total[5m])) by (name)",
     "legendFormat": "Sent on {{name}}"
    },
    {
     "expr": "- sum(irate(tomcat_global_received_bytes_total[5m])) by (name)",
     "legendFormat": "Received on {{name}}"
    }
   ]
  }
 ]
}